### ISSUE TITLE
Ignore [sub]directories

### ISSUE THREAD

**Issue by SupahNoob** [darrenburns/ward#111]
Hi!

Super excited about this project. I was hoping to ignore a certain directory/sub-directory, but I can't seem to figure out how to do this - is it possible?

My use case being that I oftentimes utilize a Jupyter Notebook to rapidly prototype. If I edit a test file in the jupyter editor, it will auto-generate a checkpoint/savepoint which has a similar name as the test file itself. `/tests/.ipynb_checkpoints/test_<thing>-checkpoint.py`

Is it possible to ignore directories ala git-ignore style or similar?

Thanks!
- SN

**Comment by SupahNoob** [comment]
doh: #70

**Comment by darrenburns** [comment]
Hey @SupahNoob! As of `0.33.0b0`, you can exclude directories in two ways.

*Using the CLI*:
```
ward --path tests --exclude .ipynb_checkpoints
```
You can pass `--exclude` more than once, to supply multiple directories to ignore. They can be glob patterns.

*Using `pyproject.toml`*:
```toml
[tool.ward]
exclude = [".ipynb_checkpoints"]  # list of glob patterns
```

Hope that helps! Let me know if you run into any issues :)
