### ISSUE TITLE
Assert that an exception is raised with a specific kind of message?

### ISSUE THREAD

**Issue by thilp** [darrenburns/ward#121]
Hello and thank you for Ward!

In the process of converting my Pytest tests to Ward, I realized that my project relies heavily on `ValueError` with some message (instead of, for example, having a large exception class hierarchy under `MyProjectError`). Accordingly, many tests look like this:
```py
def test_it_raises_on_empty_X():
  with pytest.raises(ValueError, match="empty"):
    X.parse("{}")
```

I can easily convert this test to:
```py
@test("X.parse should raise on empty inputs")
def _():
  with ward.raises(ValueError):
    X.parse("{}")
```
but that test is less precise than the original (the reported error message could be related to something else). In Pytest, the `match` keyword-argument to [`raises`](https://docs.pytest.org/en/latest/assert.html#assertraises) allows me to specify a regex the raised exception's message should satisfy.

What would you suggest in that case? My first reflex was to look at the code of `ward.raises` and be enthused over how easy it would be to add the same Pytest feature. My understanding is however that "become a Pytest clone" is not high on the list of Ward's goals (nor do I think it should be), so I shelved my pull-request for now, and I'm very curious about other ideas regular users of Ward could have about this use-case.

Ideally I would have in Ward an intuitive way to specify that my code raised an exception with some keywords in the exception's message. Rewriting the application to use a custom exception class hierarchy would solve the problem today, but would create other problems and would basically be a reason to keep Pytest alongside Ward. Please let me know how I can help!

**Comment by darrenburns** [comment]
Hey, thanks for the note :) I realise that `raises` isn't as flexible as would be required in a lot of cases. I've thought about a couple of different approaches to enabling access to the exception.

My intention was to provide this pytest-esque means of accessing the exceptions raised, but I'm definitely not settled on this approach and am open to any kind of suggestion!

What I was **considering**, was something like this:

```python
@test("X.parse should raise on empty inputs")
def _():
  with raises(ValueError) as err:
    X.parse("{}")
  assert "empty" in err
```

I don't know yet about providing something like `match` within the context manager itself. My initial though on it is it would be best to just provide access to the exception as in the example above, and let the user confirm that the exception is structured in the way they expect.

**Comment by thilp** [comment]
I really like your idea of just handing the exception to the user so that they can assert whatever they want. It also doesn't require to learn/remember a parameter name.

Would you like me to propose a PR for this, or do you want to give it more thought?

**Comment by darrenburns** [comment]
Sure, you're more than welcome to open a PR for it! 😄
