### ISSUE TITLE
If there are several errors they can be difficult to find

### ISSUE THREAD

**Issue by onlyanegg** [darrenburns/ward#124]
When several failures occur, the individual errors can be a little difficult to find. For example, here's the last page of my terminal after three tests raise exceptions

```

___________________________________________________________________________________________________________________________________________________

  Failure: search_generally query='fox' returns tests with 'fox' in the body

    Traceback (most recent call last):

      File "/home/tyler/Documents/git/ward/.venv/lib/python3.7/site-packages/ward/testing.py", line 132, in run
        self.fn(**self.args)

      File "tests/test_collect.py", line 45, in _
        raise Exception

    Exception


___________________________________________________________________________________________________________________________________________________

  Failure: search_generally returns an empty generator when no tests match query

    Traceback (most recent call last):

      File "/home/tyler/Documents/git/ward/.venv/lib/python3.7/site-packages/ward/testing.py", line 132, in run
        self.fn(**self.args)

      File "tests/test_collect.py", line 52, in _
        raise Exception

    Exception


___________________________________________________________________________________________________________________________________________________

FFF................................................................................................................................................
FAILED in 0.63 seconds [ 3 failed  1 skipped  163 passed ]
```

I need to scroll up to see all the tests that failed, and from the traceback, it's not super easy to find which tests failed.

I thought of a few things that I think could make it easier

- Have a failures-only output mode
  - Like normal mode, except it doesn't show successes (maybe this could be default)
- Show each failure on a line (similar to default mode) in summary
- Show `module:linenum [case]` in detailed failure
  - Currently, there's `Failure: <test description>`; maybe there could be `Failure: <module:linenum [case]> <description>`
- Add `details` command
  - Ward could store the results of the last test which could then be searched through in details mode
  - By default, ward would not show the stack traces, but they could be shown via `ward details` or something similar

```
$ ward
 FAIL  test_collect:35: search_generally matches on test name alone
 FAIL  test_collect:42: search_generally query='fox' returns tests with 'fox' in the body
 FAIL  test_collect:49: search_generally returns an empty generator when no tests match query
___________________________________________________________________________________________________________________________________________________

FFF................................................................................................................................................
FAILED in 0.63 seconds [ 3 failed  1 skipped  163 passed ]
$
$ ward details --search 'returns empty generator'
  Failure: search_generally returns an empty generator when no tests match query

    Traceback (most recent call last):

      File "/home/tyler/Documents/git/ward/.venv/lib/python3.7/site-packages/ward/testing.py", line 132, in run
        self.fn(**self.args)

      File "tests/test_collect.py", line 52, in _
        raise Exception

    Exception
```

**Comment by darrenburns** [comment]
> Have a failures-only output mode

For a "failures only" mode to work, we'd have to have some way of indicating that tests are progressing.

> Show each failure on a line (similar to default mode) in summary

I quite like this idea. I'm a little concerned that it might end up really verbose though in the case of a large number of failures.

> As for displaying more specific locations. This *does* happen for assertions involving comparisons (see pic below). It'd be nice to see this expanded so that it appears when any AssertionError is raised.

<img width="298" alt="Screenshot 2020-02-04 at 22 26 52" src="https://user-images.githubusercontent.com/5740731/73793213-d8259280-479d-11ea-8e0c-d38447f2a18c.png">

> Add details command 

Just to make sure I'm understanding this correctly: do you mean you'd run the tests as normal, then Ward would store the results of the last run on disk? It's an interesting idea. A pre-requisite is a cache, which is something Ward will have in the future.

> By default, ward would not show the stack traces, but they could be shown via ward details or something similar

I'm not a fan of hiding stack traces **by default**. I'm not opposed to it being an option though.

**Comment by onlyanegg** [comment]
I really like the output for the comparisons. It's really clear what's going on.

> Just to make sure I'm understanding this correctly: do you mean you'd run the tests as normal, then Ward would store the results of the last run on disk? It's an interesting idea. A pre-requisite is a cache, which is something Ward will have in the future.

Yup, that's exactly what I mean. After some thought, I agree with you that it shouldn't be the default. It would be nice to be able to have a configuration option though.
