### ISSUE TITLE
Improving exception output (hide Ward internals, better formatting)

### ISSUE THREAD

**Issue by darrenburns** [darrenburns/ward#125]
Tracebacks may contain some frames that are internal to Ward:

<img width="706" alt="Screenshot 2020-02-04 at 22 10 47" src="https://user-images.githubusercontent.com/5740731/73791974-40bf4000-479b-11ea-8c26-35704c8ea705.png">

Perhaps we could hide these as they're redundant information. I'm also interested in how we could format the exceptions better, to make them more readable. Right now, Ward adds some padding between frames and highlights the first line of each frame in blue, but I think we could do better. I got an exception in Poetry recently and noticed it was considerably easier to read due to the use of colours. There's also a couple of libraries that do some interesting things with errors, that could act as some inspiration:

**[better-exceptions](https://github.com/Qix-/better-exceptions)**:
<img width="800" alt="better-exceptions1" src="https://raw.githubusercontent.com/Qix-/better-exceptions/master/screenshot.png">

**[PrettyErrors](https://github.com/onelivesleft/PrettyErrors)**:
<img width="317" alt="Screenshot 2020-02-04 at 22 13 41" src="https://user-images.githubusercontent.com/5740731/73792155-a3b0d700-479b-11ea-8e38-1668ef4d8643.png">

**Comment by thebigmunch** [comment]
Here's another example to add to the list of libraries that do interesting things with tracebacks: https://www.willmcgugan.com/blog/tech/post/better-python-tracebacks-with-rich/

**Comment by darrenburns** [comment]
@thebigmunch that looks very interesting in general. It seems to solve some of the main issues I have around terminal output in Ward -- mostly relating to maintainability and testability. I'm considering moving all terminal output over to it, as it solves some of the common problems I hit in a consistent manner.

**Comment by darrenburns** [comment]
Closing -- Ward now uses Rich for exception output 🎉
