### ISSUE TITLE
How would you use ward with asyncio/trio/curio?

### ISSUE THREAD

**Issue by SupahNoob** [darrenburns/ward#131]
```python
from ward import test, xfail


@xfail('but seriously.')
@test('async functions should fail')
async def _():
    assert False
```
Naturally this should not pass, but indeed it does.
![image](https://user-images.githubusercontent.com/14192437/75100515-273c3780-5594-11ea-9d91-0067605475ff.png)

So I tried writing a decorator just to see if I could force the async to be sync.
```python
import functools as ft
import asyncio

from ward import test, xfail


def async_test(fn):
    @ft.wraps(fn)
    def _async_wrapper(*args, **kwargs):
        loop = asyncio.get_event_loop()
        return loop.run_until_complete(fn(*args, **kwargs))

    return _async_wrapper


@xfail('but seriously.')
@test('async functions should fail')
@async_test
async def _():
    assert False
```
and it passed! ... but I know for certain it's not actually working. I can put literally anything in the anon function under `@async_test` and ward will tell me it passes.

So my assumption is that ward currently will not support async testing... but maybe I'm not smart enough to figure it out. :~)

\- SN

**Comment by darrenburns** [comment]
You're correct, Ward doesn't have proper built-in support for this, but it's something I want to add. The only way I can think of doing this right now is to define the async test inside a standard synchronous test like so:

```
def run_async(coro):
    return asyncio.get_event_loop().run_until_complete(coro)


@fixture
def two():
    yield 2


@test("async test")
def _(two=two):
    async def test_coro():
        assert 1 == two

    run_async(test_coro())

```

**Comment by darrenburns** [comment]
Just as an update to this, after thinking about it I've got an update planned that'll allow you to define your tests with `async def` and just use the standard `@test` decorator:

<img width="482" alt="Screenshot 2020-02-23 at 16 00 05" src="https://user-images.githubusercontent.com/5740731/75115370-b52c2700-5655-11ea-85d7-696111af0362.png">

It still needs work, but hopefully this will land soon!

**Comment by darrenburns** [comment]
Hey @SupahNoob. Ward 0.37.0b0 has support for `async def` tests and fixtures. That is, the existing `@fixture` and `@test` decorators now work with `async` functions.

If you give it a try let me know how it goes or if you run into any problems! :)

**Comment by SupahNoob** [comment]
@darrenburns sorry for getting back to this so late, life sometimes catches up to you in a way :~)

I believe the test runner is firing the async tests off sequentially. In building out some tests for a web request rate limiter, I found that my tests were taking longer than I'd expected. I wrote up a little example to demonstrate. In normal async cases, you'd expect the total amount of time spent in test to be closer to 5.31s (collection + singular maximum test time).

![image](https://user-images.githubusercontent.com/14192437/77230106-ea963880-6b5f-11ea-87a4-c6704e578dd1.png)


```python
import asyncio
import time

from ward import test, each

@test('async test: sleep({zzz})')
async def _(zzz=each(5, 3)):
    start = time.monotonic()
    await asyncio.sleep(zzz)
    elapsed = time.monotonic() - start
    assert round(elapsed) == zzz
```

**Comment by darrenburns** [comment]
Hi @SupahNoob, this is as intended -- `async` tests are run sequentially. An `async` test runs asynchronous code on the event loop, but it waits until the test is complete before continuing on to the next test. So code **within** an async test is run asynchronously, but multiple `async` tests don't exist on the event loop at a given time (that would cause several issues).

In other words, the tests themselves can be asynchronous, but the runner is not. It may be possible to have a separate asynchronous runner that users can opt-in to, but that'd be a looong way off likely :)

**Comment by SupahNoob** [comment]
Interesting. I'm admittedly new to the world of async testing, so I'm not aware of what is/isn't standard practice. It makes sense to me why there is a need for a synchronous runner, even if tests are async in isolation.
