### ISSUE TITLE
Option to print failure output as soon as failure happens

### ISSUE THREAD

**Issue by darrenburns** [darrenburns/ward#132]
Rather than waiting until all tests have run, there could be an option to print failure output as soon as the failure happens.

**Comment by blueyed** [comment]
That's very useful, especially with long test runs.

(For pytest there is https://github.com/pytest-dev/pytest-instafail, but I plan to have something like that with pytest itself already.)

**Comment by darrenburns** [comment]
Indeed - I actually first found out about the idea via another pytest plugin: pytest-sugar.
