### ISSUE TITLE
attaching debugger in pycharm

### ISSUE THREAD

**Issue by dodgyville** [darrenburns/ward#137]
Hi,

This more of a pycharm question I guess so no worries if you don't want to answer it. Do you know how to run a ward test from within pycharm? It's great to be able to set breakpoints from there

**Comment by darrenburns** [comment]
If you mean being able to click on the little icon in the gutter to run individual tests that'd probably require someone to develop a PyCharm plugin. As for attaching a debugger: I'm not sure. I imagine you'd be able define a run configuration and set the script path to be the path to Ward.

**Comment by darrenburns** [comment]
Closing this for now to clean up the issues a bit. Don't hesitate to re-open if you'd like to continue the discussion though 😄

**Comment by WolfDWyc** [comment]
Just updating, the best way I found on how to do this:

Create a file called run_ward.py:

```python
from ward import _run
_run.run()
```

Also make sure to check "Emulate terminal in output console" to get colored output.

@darrenburns Let me know if there's a better way.
