### ISSUE TITLE
Use Poetry

### ISSUE THREAD

**Issue by darrenburns** [darrenburns/ward#141]
I've been using Poetry as part of my debugger project ([Pybreak](https://github.com/darrenburns/pybreak)) and am enjoying the experience of developing locally with it more than I am with Flit, which Ward currently uses. I'd be interested in switching Ward over to use Poetry. 

If anyone has any thoughts on this or if they'd like to give it a go, let me know!

**Comment by thebigmunch** [comment]
I have used poetry for my projects for a long time. Even tested its predecessor pypoet when it was first coming onto the scene. So I'm definitely for it.

**Comment by darrenburns** [comment]
Poetry is now used for dependency management, building, and publishing as of 0.41.0b0.
