### ISSUE TITLE
Running in parallel: Splitting tests across multiple processes/workers

### ISSUE THREAD

**Issue by darrenburns** [darrenburns/ward#146]
`ward -n 4`, or possibly `ward --workers 4` would distribute all discovered tests across 4 processes.

**Comment by pawamoy** [comment]
This would be extremely useful for projects with big test suites.

One thing I noticed from `pytest-xdist` that could be improved, is that workers are given a share of the test suite at collection time, and so might be unbalanced: some workers will finish very fast while others will finish very slowly depending on the tests they were given.

If parallelization gets implemented in ward, maybe this could be improved with a master process that feeds tests one by one to workers that are available? Each worker is idling, waiting for a test to run, runs it immediately when received, then waits again. The master process gives a test to a worker as soon as it says "I'm available".

What do you think?

**Comment by darrenburns** [comment]
I agree it'd be really useful. I did a quick hack around this a while back to see what would be involved, using a `ProcessPoolExecutor` amongst other approaches. This would've sent tests to processes as tests became available. 

I ran into problems with pickling though, I think it's possibly because test functions were named `_`, but I haven't verified that and didn't dig into whether giving test functions names other than `_` make them picklable or not.

**Comment by pawamoy** [comment]
I suppose your work is in the `parallel` branch if I want to take a look?

**Comment by darrenburns** [comment]
That branch only has the groundwork for structuring things a bit clearer to allow for parallel execution, it doesn't actually attempt to run anything in parallel yet. My experimentation with `ProcessPoolExecutor` was, if I remember correctly, rewriting a single method. 

This method from the `parallel` branch (which is copy-pasted from the existing sequential code) would need to be re-implemented to use a ProcessPoolExecutor or similar approach to parallelism: https://github.com/darrenburns/ward/blob/6c4e8a8e95cb5abe937d3497766d523c081e18dc/ward/terminal.py#L394. 

It takes a generator of `TestResults`, which, when iterated over actually runs the tests. Allowing that iteration to happen over multiple processes and have the results collected in the parent process was my goal 😄
