### ISSUE TITLE
Discussion: To what extent should terminal output be tested?

### ISSUE THREAD

**Issue by darrenburns** [darrenburns/ward#149]
This is an open question/discussion, happy for anyone with an opinion to chime in as always!

Terminal output is a blind spot in Ward's test coverage. There are two main reasons for this:
* I'm not happy with the code around terminal output and want to migrate it to using a higher level framework such as [Rich](https://github.com/willmcgugan/rich) - so don't want to commit to writing lots of tests for it when they'd be getting removed soon.
* I'm skeptical of the advantage to maintenance burden ratio of adding tests around such code. Is being dilligent when making changes that affect output enough? Is this an area where manual testing is a better solution than automated testing?

Any thoughts would be welcome 😄

**Comment by thebigmunch** [comment]
Unit test any component parts you can, sure, but don't worry about integration testing much. If possible, break things down as much as you can into separate components (if not already as atomic as possible), so you can unit test the parts. Then testing them as a whole is better done by usage.
