### ISSUE TITLE
Convenient way to define large each

### ISSUE THREAD

**Issue by JoshKarpel** [darrenburns/ward#168]
While working on https://github.com/darrenburns/ward/pull/161, I ended up writing this test:

```python
@test("group {items!r} by {key} returns {result}")
def _(
    items=each(range(5), "echolocation", [-2, 3, 4, -3, 2, 3]),
    key=each(is_even, is_vowel, square),
    result=each(
        {True: [0, 2, 4], False: [1, 3]},
        {True: ["e", "o", "o", "a", "i", "o"], False: ["c", "h", "l", "c", "t", "n"]},
        {4: [-2, 2], 9: [3, -3, 3], 16: [4]},
    ),
):
    assert group_by(items, key) == result
```

I think three is about the last number of test cases where it becomes easy to track the "parallel each" construction that's going on. I really like `each` for easily parameterizing tests with either just one varying input, or with a small number of total cases, but I think it can become unwieldy when you expand past that.

I propose a new way of parameterizing a test, where the values can be defined in packed tuples in advance, keeping each test case's values together. Maybe something like this (which would produce exactly the same tests as above)...

```python
@test("group {items!r} by {key} returns {result}")
@params(
    [
        (range(5), is_even, {True: [0, 2, 4], False: [1, 3]}),
        (
            "echolocation",
            is_vowel,
            {
                True: ["e", "o", "o", "a", "i", "o"],
                False: ["c", "h", "l", "c", "t", "n"],
            },
        ),
        ([-2, 3, 4, -3, 2, 3], square, {4: [-2, 2], 9: [3, -3, 3], 16: [4]}),
    ]
)
def _(
    items=each_from_params(0), key=each_from_params(1), result=each_from_params(2),
):
    assert group_by(items, key) == result
```

This would be a sort of hybrid between the pytest and ward approaches to parameterization.

Thoughts?

**Comment by darrenburns** [comment]
Thanks for the suggestion. I've had the exact though before, and `each` is one of my least favourite things about ward and I agree with everything you said.

My initial thoughts on looking at the proposed example is that I'm not a fan of `each_from_params(idx)`, but I'll take some time to think about this and see if I can come up with anything.

**Comment by darrenburns** [comment]
Was thinking this over again and am wondering if the pytest approach is something we should add, or just implictly passing in the params like so:

```python
@test("group {items!r} by {key} returns {result}")
@params(
    [
        (range(5), is_even, {True: [0, 2, 4], False: [1, 3]}),
        (
            "echolocation",
            is_vowel,
            {
                True: ["e", "o", "o", "a", "i", "o"],
                False: ["c", "h", "l", "c", "t", "n"],
            },
        ),
        ([-2, 3, 4, -3, 2, 3], square, {4: [-2, 2], 9: [3, -3, 3], 16: [4]}),
    ]
)
def _(
    items, key, result
):
    assert group_by(items, key) == result
```

**Comment by JoshKarpel** [comment]
Would
```python
@test("group {items!r} by {key} returns {result}")
@params(
    [
        (range(5), is_even, {True: [0, 2, 4], False: [1, 3]}),
        (
            "echolocation",
            is_vowel,
            {
                True: ["e", "o", "o", "a", "i", "o"],
                False: ["c", "h", "l", "c", "t", "n"],
            },
        ),
        ([-2, 3, 4, -3, 2, 3], square, {4: [-2, 2], 9: [3, -3, 3], 16: [4]}),
    ]
)
def _(
    items, key, foo=each(1, 2, 3), result
):
    assert group_by(items, key) == result
```
do the cross-product of the `each` and the `params` (resulting in 3 * 3 = 9 tests), or does it get aligned with them and you only end up with 3 cases? Can you put two `@params` on a test and get a cross-product? (You can in pytest, but I've often preferred using `itertools` to build up the cases manually.)

Presumably in this case you skip `foo` and assign the last element of each parameter group to `result`, because `foo` is already set. Same if `foo` was set to a fixture. Roughly the same as pytest without needing to write out the argument names.

One nice thing about `each_from_params(idx)` is that it's very explicit about that behavior. I won't claim it's pretty though, and I often like the implicit magic :)

Another possibility would be to pass dictionaries, like
```python
@test("group {items!r} by {key} returns {result}")
@params(
    [
        {"items": range(5), "key": is_even, "result": {True: [0, 2, 4], False: [1, 3]}},
        {
            "items": "echolocation",
            "key": is_vowel,
            "result": {
                True: ["e", "o", "o", "a", "i", "o"],
                False: ["c", "h", "l", "c", "t", "n"],
            },
        },
        {
            "items": [-2, 3, 4, -3, 2, 3],
            "key": square,
            "result": {4: [-2, 2], 9: [3, -3, 3], 16: [4]},
        },
    ]
)
def _(items, key, result):
    assert group_by(items, key) == result
```
Which would let you be explicit about which value is for which argument without needing `each_from_params`, but is so verbose that I almost couldn't bear to type it out for the example...

Another thing I've been thinking about is how Jest handles this (I have also been writing some Typescript lately...). In Jest you can just build up tests in a loop. Ward would be pretty amenable to that pattern because the decorator immediately captures the required context. So one path forward might be to keep `each` for simple aligned parameterization, and punt to the language itself for more complex patterns.
