### ISSUE TITLE
Ward not importing module

### ISSUE THREAD

**Issue by maurosilber** [darrenburns/ward#172]
The module where a test is defined is not in `sys.modules` during test run, which makes this test fail:

```python
# test_ward.py
from typing import get_type_hints

from ward import test


@test("Get type hints")
def _():
    class A:
        x: int

    get_type_hints(A)
```
with the following error:
```python
Failure: Get type hints

    Traceback (most recent call last):
    
      File ".../lib/python3.8/site-packages/ward/testing.py", line 143, in run
        self.fn(**resolved_args)
    
      File "examples/test_ward.py", line 11, in _
        get_type_hints(A)
    
      File ".../lib/python3.8/typing.py", line 1223, in get_type_hints
        base_globals = sys.modules[base.__module__].__dict__
    
    KeyError: 'test_ward'
```

That is, `test_ward` is not in `sys.modules`.

I'm not sure this is the intended behaviour, but it works in pytest:

```python
from typing import get_type_hints

def test_get_type_hints():
    class A:
        x: int

    assert get_type_hints(A) == {"x": int}
```

I had this same issue recently with a test that used a numba-compiled function. Numba also searches for the functions' module in `sys.modules` as part of the compilation. I worked around that issue by writing the function in a different module which was then imported in the test module.

By the way, thank you for developing Ward!

**Comment by darrenburns** [comment]
Thanks for the report :) This was fixed in 0.52.1b0, let me know if you have any more issues!
