### ISSUE TITLE
A `--color` argument to force color output

### ISSUE THREAD

**Issue by silverwind** [darrenburns/ward#174]
I'm running ward on a continous integration that is capable of outputting color but some mechanism in ward's the color output prevents it from coloring, presumably because stdout is not a TTY.

Suggesting a `--color` argument like [jest's](https://jestjs.io/docs/en/cli#--colors). Ideally both `--color` and `--colors` should be acceptable to stay consistent with jest (if that is a goal).

**Comment by darrenburns** [comment]
Ward now uses Rich for most terminal output, which I believe handles this sort of thing. There are still some areas to migrate over to Rich, but hopefully this is fixed in the majority of cases.

**Comment by silverwind** [comment]
Not sure how Rich detects color support, but with [environment detection](https://github.com/chalk/supports-color/blob/1e7f117cda1284e741c3cbcd661c21412bf169eb/index.js#L97-L99) most CI environments can be made to use color automatically. Still I guess a `--color` argument may be nice to have for cases where auto detection fails.
