### ISSUE TITLE
hypothesis tests do not work anymore

### ISSUE THREAD

**Issue by MrGreenTea** [darrenburns/ward#177]
As already noted in [ #69](https://github.com/darrenburns/ward/issues/69#issuecomment-665272190) the `hypothesis` integration is broken currently.

I tracked it down and believe the cause lays in the way assertions are rewritten.
Because [here in rewrite.py](https://github.com/darrenburns/ward/blob/master/ward/rewrite.py#L124) the code object is only the body of the function all associated functionality by `@hypothesis.given` is lost. I assume this will be the same for all decorators that don't directly return the function itself.

This can be reproduced with
```py
from ward import test
from hypothesis import given, strategies


@test("hypothesis example")
@given(a=strategies.integers())
def _(a):
    assert isinstance(a, int)
```

**Comment by darrenburns** [comment]
Thanks for the report. I should remove the Hypothesis integration stuff from the docs. That functionality isn't included in test coverage and so shouldn't be advertised as a feature.

I'm also open to pull requests to fix the integration and add test coverage around it. It's a nice-to-have but I have very little time to work myself at the moment.

**Comment by MrGreenTea** [comment]
> Thanks for the report. I should remove the Hypothesis integration stuff from the docs. That functionality isn't included in test coverage and so shouldn't be advertised as a feature.
> 
> I'm also open to pull requests to fix the integration and add test coverage around it. It's a nice-to-have but I have very little time to work myself at the moment.

I am looking into it right now. I would also like to work on the hypothesis integration and add some integration tests.
Thanks for the work on this tool, it's already very nice to use and if we manage a deeper integration with `hypothesis` we hope to switch from `pytest`.

**Comment by darrenburns** [comment]
Thanks, I appreciate it!

**Comment by darrenburns** [comment]
The new documentation no longer mentions Hypothesis. I'm going to close this off, and if you'd still like to work on a Hypothesis integration feel free to open a discussion! :)

**Comment by MrGreenTea** [comment]
Yeah makes sense. Sadly I was very busy with my bachelor thesis but want to start contributing to `ward` in the next weeks :)

**Comment by darrenburns** [comment]
I know the feeling 🙂 good luck!
