### ISSUE TITLE
Diff colors make the diff unreadable

### ISSUE THREAD

**Issue by marcoacierno** [darrenburns/ward#209]
this is the output:

```
  Comparison: LHS vs RHS shown below

    cs_session_cus_hello
    cs_session_cus_test_1

  Location: association_membership/tests/domain/services/test_subscribe_user_to_association.py:75
```

but it's printed like this in the console:

<img width="316" alt="image" src="https://user-images.githubusercontent.com/3382153/115122936-98b62100-9fb2-11eb-825c-42451d4e1db0.png">

The diff is unreadable

Not sure if it's an issue with my iTerm2 colors configuration or something else! Happy to give more information

**Comment by darrenburns** [comment]
Hi!

This is probably an issue in your colours configuration. You can configure the green/red background and foreground colours in the preferences, and you need to make sure they're different and appear correctly on top of each other.
