### ISSUE TITLE
Rewrite diff code using Rich

### ISSUE THREAD

**Issue by darrenburns** [darrenburns/ward#211]
The code in `diff.py` is pretty much the final location in Ward that isn't using Rich for terminal output. We should update it to use Rich, which should also allow us to more easily add test coverage around this area.

I've put this as a "Good First Issue" because the diff code is fairly de-coupled from the rest of Ward.

**Comment by alanbato** [comment]
I'll try to tackle this :) Any pointers are appreciated.

**Comment by darrenburns** [comment]
Maybe worth checking with @willmcgugan to see if he has any pointers or if he's planning on writing this functionality in a separate library. He mentioned on Twitter he was considering it.

**Comment by willmcgugan** [comment]
Happy to help! I did have an idea to implement a diff renderable, but it wouldn't happen for a while.

You probably want to use the [console protocol](https://rich.readthedocs.io/en/latest/protocol.html) to create a renderable Diff object. So you create an instance, and then print it with the console. Something like this:

```python
my_diff = Diff(code)
console.print(my_diff)
```

The existing renderables all use this protocol. See the code [here](https://github.com/willmcgugan/rich/tree/master/rich), in particular syntax.py which you will probably want to use as a reference.

Mention me if you have any questions...

**Comment by darrenburns** [comment]
Definitely agree on the console protocol usage. 

The plugin/hook system is going to make use of it extensively (e.g. return an object from your hook that implements the rich console protocol, and rich will render it). [Here's]( https://github.com/darrenburns/ward/pull/210/files#diff-c9720b1eb34ed79a5e3a528e5b9ae3e00f0595a259f9815b3dad3d75558bae0fR35-R58) an example.

I'm looking to rewrite most terminal output code to use it too, as I think it's currently only used in one or two places in Ward.

**Comment by alanbato** [comment]
Submitted the PR above, cheers :)
