### ISSUE TITLE
Upgrade to Click v8

### ISSUE THREAD

**Issue by darrenburns** [darrenburns/ward#212]
Click 8.0.0 was released. We should upgrade to it, and ensure that everything still works as expected.

**Comment by AABur** [comment]
Based on the changes in the `click` library, the upgrade from version 7.0 to version 8.0 does not contain breaking changes to the `ward` code.
It comes down to a simple replacement in `pyptoject.toml 
`click = "^7.0"` -> `click = "^8.0"`

I'm ready to implement it

**Comment by darrenburns** [comment]
Thanks @AABur! If you'd like to make that change and run `make prep` (to update the .lock file), then take `ward` for a quick spin to ensure no regressions, that'd be much appreciated.

**Comment by AABur** [comment]
Done!
My PR #215 requires approval to pass CI workflow
