### ISSUE TITLE
python_implementation and python_version in --version output

### ISSUE THREAD

**Issue by AABur** [darrenburns/ward#216]
https://github.com/darrenburns/ward/blob/e652a47090fcd9013fd2c95d08aa611c7fc6905b/ward/terminal.py#L350

RE: #214 

Commit [3fb6da6](https://github.com/darrenburns/ward/commit/761cdf90cf262a7dac53fcdc1213dfc1b3fb6da6) removed `python_impl` and `python_version` from the `--version` output. Consequently, linter check complains about unused variables (F841).

There are two solutions:
- return the two "lost" parameters back
- remove unused variables - this information not needed anymore

Which solution is better?

**Comment by darrenburns** [comment]
When @JoshKarpel's PR is merged, they'll be used. Feel free to just remove them for now
