### ISSUE TITLE
Add Python 3.10 Beta support to CI

### ISSUE THREAD

**Issue by darrenburns** [darrenburns/ward#228]
Our GitHub Actions only run Python 3.6 - 3.9.

I tried adding 3.10 beta a while back, but ran into some issues as I don't think it was available on GitHub Actions at that point.

I'd like to see this added back in soon to ensure that we're prepared for the full 3.10 release.

**Comment by Catastrophe0123** [comment]
Hey @darrenburns,

I guess adding 3.10.0-beta.1 to the build matrix should work right?

Can I raise a PR?

**Comment by darrenburns** [comment]
> Hey @darrenburns,
> 
> 
> 
> I guess adding 3.10.0-beta.1 to the build matrix should work right?
> 
> 
> 
> Can I raise a PR?

@Catastrophe0123 Of course, that'd be great. I think that'd be enough. I believe there are two similar build matrices so you might need to add it in two places. If you raise a PR with that in it we can see if it runs 🙂
