### ISSUE TITLE
Use correct plural vs singular depending on number of tests and fixtures collected

### ISSUE THREAD

**Issue by darrenburns** [darrenburns/ward#244]
At the top of the output, we print the number of tests and fixtures collected:

<img width="900" alt="image" src="https://user-images.githubusercontent.com/5740731/120119888-0e0c3880-c192-11eb-846e-08bb91c64066.png">

If we collect only 1 test or 1 fixture, we should write `test` instead of `tests`, and `fixture` instead of `fixtures` to the terminal.

**Comment by asadafasab** [comment]
Hi, I would like to work on this issue.
