### ISSUE TITLE
Issue with pinning click to 8

### ISSUE THREAD

**Issue by cheginit** [darrenburns/ward#271]
First, thanks for this package, it's intuitive and visually appealing! I have already migrated one of packages ([AsyncRetriever](https://github.com/cheginit/async_retriever)) from `pytest` to `ward`. However, I am facing some issues with migrating my other packages due to dependency conflicts.

In `pyproject.toml` version of `click` is set be at least 8. Are you using any specific feature of `click` 8 in `ward`? Since many packages still haven't upgraded to `click` 8, installing `ward` causes conflict. For example, `fiona` which is a popular package and is a dependency for many other packages still uses `click` 7. If `click` 8 is not a hard dependency, setting the minimum version to 7 will make migrating to `ward` easier.

**Comment by darrenburns** [comment]
> First, thanks for this package, it's intuitive and visually appealing!

Thanks 😄 

> If click 8 is not a hard dependency, setting the minimum version to 7 will make migrating to ward easier.

I agree, we should probably mark click as `>=7.0.0`. We're not using any Click 8 features. Pinning it to 8 rather than `>=7` was an oversight, because Ward should work with both.
