### ISSUE TITLE
Is there equivalent of monkeypatching for ward?

### ISSUE THREAD

**Issue by kitcatkai** [darrenburns/ward#273]
I recently tried this library and really like the terminal interface to highlight any error and pass.

I will like to know if there is any equivalent of monkeypatch? 

https://docs.pytest.org/en/6.2.x/monkeypatch.html

**Comment by darrenburns** [comment]
Hello, thanks for the feedback!

I'd recommend using the `mock.patch.object` and `mock.patch.dict` context managers, which are part of the Python standard library. Here's some examples:

This example replaces `Path.cwd`, to simulate running the code from different directories:
https://github.com/darrenburns/ward/blob/3bc5de8cf62c6e815bbda165f5b3a3a64d9090af/tests/test_debug.py#L44-L47

This example shows how to replace an environment variable:
https://github.com/darrenburns/ward/blob/c01a45708e42f38bd5550dae941aaf8286a46baf/tests/test_config.py#L171-L172

**Comment by kitcatkai** [comment]
Thanks for your suggestion. I have tried below and it worked but it looks kind of clunky: no separation of concern between flask and the patch object. Is there a way to break them apart yet setting them as global fixtures?

@fixture(scope="global")
def test_client():
    flask_app = create_app(TestConfig)
    with flask_app.test_client() as testing_client:
        with flask_app.app_context():
            with patch.object(Extract, "userid", return_value=130):
                yield testing_client

**Comment by JoshKarpel** [comment]
@kitcatkai you could split that into two fixtures, like

```python
@fixture(scope="global")
def test_client():
    flask_app = create_app(TestConfig)
    with flask_app.test_client() as testing_client:
        with flask_app.app_context():
            yield testing_client


@fixture(scope="global")
def test_client_with_mocked_userid(test_client=test_client):
    with patch.object(Extract, "userid", return_value=130):
        yield test_client
```
