### ISSUE TITLE
[Feature Request] Would be nice to be able to mark tests to be run in subprocess for better isolation

### ISSUE THREAD

**Issue by taranlu-houzz** [darrenburns/ward#276]
I have some tests that need to inspect the state of `sys.modules` to ensure correct behavior with lazy loading. I would like to keep my tests randomized, but unfortunately, because they appear to all be gathered and then run in the same context, the order can mess with what modules are loaded when, which causes any given test run to pass or fail randomly.

I was wondering if it might be possible to add a feature such that a test can be marked a needing to be run in a subprocess, so that it can have a completely clean environment?

**Comment by darrenburns** [comment]
Having tests depending on the state of `sys.modules` sounds like a bad idea. Any chance you'd be able to share a little more of what you're trying to do so I can try and understand your use-case more?

**Comment by taranlu-houzz** [comment]
I'm writing some tests to confirm correctness for lazy loading modules using `importlib`. Basically, I need to be able to check that my lazy loading function primes the modules for loading (but does not actually load) them, that it survives a reload before actually loading the module, etc. Since I would also like to use random test order execution, this causes issues if other tests fully load the modules that are lazy loaded.

**Comment by darrenburns** [comment]
I think I see what you mean.

Would `NamedTemporaryFile` work? You could use that inside a fixture which gets injected into the relevant tests. That fixture would create a temporary `.py` file (or set of directories) which you could lazy load. In the teardown code for that fixture, the temporary file would be deleted.

For the "run test in a subprocess" thing, I think that's something that might be a bit too niche for Ward itself and would be better suited to a [plugin](https://ward.readthedocs.io/en/latest/guide/plugins.html) (or you could just implement the hook function in your own project). Although, I'm not sure any of the hooks are entirely suitable for this use case at the moment.

You could have a look at [this hook](https://ward.readthedocs.io/en/latest/guide/plugins.html#filter-sort-or-modify-collected-tests-with-preprocess-tests), which lets you modify `Test` objects after they're collected and you could try replacing/wrapping `Test.run` with a version that spawns a subprocess. I can't say what issues you may run into when trying that though, I'm just throwing out ideas 😄

**Comment by taranlu-houzz** [comment]
Hmm, yeah, I suppose that could work. Honestly, the code I have works fine from manual testing, it was more that I wanted it to be covered by unit tests as well, but like you said, it is a bit niche and the work that would go into making that possible would be non-trivial. It would also probably make interfacing with `coverage` a bit tricky as well (I have not had good luck getting subprocesses to be covered correctly; I tried following the suggestions in their docs specifically for that, but it didn't work for me).

Anyway, thanks for the response!
