### ISSUE TITLE
Allowing multiple assertion failures per test

### ISSUE THREAD

**Issue by darrenburns** [darrenburns/ward#286]
A mechanism for having multiple failures per test. In other words, an `assert` failing wouldn't result in a fail-fast for that test. Any remaining assertions would execute, and they'd all be displayed.

https://github.com/darrenburns/ward/pull/256#issuecomment-869049499

The interface is still undecided, but I would like to see this be configurable down to a per-test, and possibly even a per-assert level.

**Comment by hukkin** [comment]
IMO would be best to keep behavior of the `assert` statement as is. The `assert` statement is expected to raise an exception and (unless explicitly caught) exit the function scope. Not doing so is unlike normal Python behavior, and can easily lead to unexpected infinite loops and other weirdness.

I'm also generally not a fan of the concept, as I feel like the need for it probably signals that a test that should be refactored (split or parameterized). I may be wrong here though.

**Comment by JoshKarpel** [comment]
> IMO would be best to keep behavior of the `assert` statement as is. The `assert` statement is expected to raise an exception and (unless explicitly caught) exit the function scope. Not doing so is unlike normal Python behavior, and can easily lead to unexpected infinite loops and other weirdness.
> 
> I'm also generally not a fan of the concept, as I feel like the need for it probably signals that a test that should be refactored (split or parameterized). I may be wrong here though.

I'm in the same camp...

BUT

the idea of being able to configure it per-`assert` is at least interesting to me from a syntax perspective, and possibly lightweight enough that it could be added with minimal changes to the overall framework. That might be a good way to balance the desire to use it in certain specific situations with the impact it would have on the overall design.

With https://github.com/darrenburns/ward/pull/256 we inspect non-string assertion messages. What if you could put a special constant from `ward` into your assert message to get special behavior? Something like

```python
from ward import FAIL_SLOW

...

assert foo == bar, FAIL_SLOW 
```
or maybe an enum, like
```python
class FailStyle(Enum):
    FAIL_SLOW = "fail_slow"
    ???????
```
Are there other "failure styles" that could be interesting?

Of course, that means you can't customize the assert message for such an assert....

**Comment by hukkin** [comment]
Yeah @JoshKarpel I think those would be the most intuitive ways. Also not impossible to make it take in an exception message:
```python
from ward import FAIL_SLOW

# FAIL_SLOW is a callable
assert foo == bar, FAIL_SLOW("message here")

# a tuple (fail_type, message) after the assert
assert foo == bar, (FAIL_SLOW, "message here")
```

---

Yet still, I feel like this as a change is fundamental enough that IMO one can not say that the tests are written in Python anymore. It's then Ward-Python or whatever you want to call it :smile:

Could be compared to a change where something like
```python
return True, CONTINUE
```
no longer returns but acts as a continue statement.

**Comment by JoshKarpel** [comment]
Good point about the messages!

If it's part of handling the assertion message, I wonder if this behavior can be deferred to a plugin? Then the core library just needs to expose a general purpose `on_assertion_failure` hook that can decide whether to end the test or not flexibly.

**Comment by darrenburns** [comment]
Thanks for the feedback! 

I like the ideas around using the assertion message and about agree about making it a plugin.

I agree that this might be a little too "magical" for the core lib. That, combined with the fact that it's not going to be a use-case everyone needs, means that a plugin is probably the best place for this. In this way, you could "opt in" to the magic where it offers value.
