### ISSUE TITLE
Can I centralize my fixtures into a single file?

### ISSUE THREAD

**Issue by rn4n** [darrenburns/ward#288]
I came from pytest, met Ward recently and am loving the ease of writing tests as well as the detailed report.

However, reading the documentation, I couldn't find a way to centralize the fixtures used in my test. Is it possible to centralize fixtures on a specific file that will be read by Ward? In pytest, it would be equivalent to the use of `conftest.py`, something like:

```py
# tests/conftest.py

from ward import fixture

@fixture
def project_name() -> str:
    return "ward"
```
```py
# tests/test_project.py

from ward import test

@test("should validate the project name")
def _(project_name):
    assert project_name == "ward"
```

If it's not possible to create fixtures in this way, I'd like to propose it as a feature request.

**Comment by rn4n** [comment]
**PS**: I read the [contribution guide](https://github.com/darrenburns/ward/blob/master/.github/CONTRIBUTING.md), but I sent this question as issue because I'm not allowed to see/post something in the [discussions](https://github.com/darrenburns/ward/discussions).

**Comment by darrenburns** [comment]
Hi, I've switched discussions off as I found them to be too similar to how we were using issues.

Ward doesn't have an equivalent of `conftest`. You can define fixtures anywhere you like, you just need to import them and bind them as a default param:

```python
# tests/test_project.py

from ward import test
from wherever.you.like import project_name  # import your fixture

@test("should validate the project name")
def _(p=project_name):  # supply the fixture to the test
    assert p == "ward"
```

This keeps things more explicit as you're not relying on name-matching, and you know exactly what fixture you're going to get.

Hope that helps :)

**Comment by rn4n** [comment]
Thanks @darrenburns. 🚀
