### ISSUE TITLE
Test that no exceptions were raised

### ISSUE THREAD

**Issue by JosephTLyons** [darrenburns/ward#319]
I'm currently using the following, which Is fine, but I was curious if Ward had something that replaces this pattern:

```python
try:
    function()
    assert True
except:
    assert False
```

**Comment by JoshKarpel** [comment]
A test passes if it doesn't fail, so just
```
function()
```
should be sufficient. If an exception was raised during `function()`, the test would fail automatically.

**Comment by JosephTLyons** [comment]
Ah yeah, that makes a lot of sense.  I guess I'm just not used to seeing an assertion-less test, but since `assert` just raises an `AssertionError` in the failing case, I'm guess that is what is used by the testing framework for it to pass or fail, then any sort of assertion should do the same.  Ok, thanks, I'll go ahead and close this one out.
