### ISSUE TITLE
Fixtures -- how to pass arguments to them?

### ISSUE THREAD

**Issue by mgzenitech** [darrenburns/ward#332]
Is there a way to do something similar to pytest request.param ?

```python
from typing import Callable
from pytest import fixture, FixtureRequest

@fixture(scope = "function")
# pylint: disable-next=unused-variable
def exception_function(request: FixtureRequest) -> Callable:
    def exception():
        raise Exception(request.param)
    return exception
```

Can't figure out a way to pass exception message ("Test") dynamically to the fixture from a test:
```python
from unittest.mock import MagicMock
from ward import fixture

@fixture
def mocker() -> MagicMock: # pylint: disable=unused-variable
    return MagicMock

@fixture
def exception_function(mocker: MagicMock = mocker) -> MagicMock: # pylint: disable=unused-variable
    return mocker(side_effect = Exception("Test"))
```

Any ideas?

**Comment by darrenburns** [comment]
There's no equivalent to `request.param` although I think it could be a nice feature to have.

I'm not 100% sure I understand what you're trying to achieve in your snippets, but here's a bit of (kind of unrealistic) code that might give you some ideas of how tests can be parameterised.

```python
for exception_message in ["Test Msg", "Another Msg"]:

    @test("The exception has the message '{message}'", tags=["example"])
    def _(message=exception_message):
        # Define the mock each time - you could pull MagicMock(...) into utility function too
        m = MagicMock(side_effect=Exception(message))
        with ward.raises(Exception) as e:
            m()
            assert message == str(e.raised)
```

<img width="971" alt="image" src="https://user-images.githubusercontent.com/5740731/173232329-22ec5f0a-50fe-44a2-be11-f7242c1edc6b.png">

I would also advise against using fixtures like that. I recommend only making fixtures for set-up/teardown code that is computationally expensive (which you'll cache using `scope`), or if there are multiple lines you want to avoid duplicating (but even then, consider just defining a function and calling it inside your test).

If you're able to provide the full equivalent pytest fixture *and* test showing what you're looking to achieve, I might be able to help more 🙂

**Comment by mgzenitech** [comment]
Yep, ended up just creating fixtures which return functions
