### ISSUE TITLE
Multiple fixtures with different scopes do not work as expected

### ISSUE THREAD

**Issue by mgzenitech** [darrenburns/ward#335]
__fixtures.io.tmp_dir.py
```python
#!/usr/bin/env python3

from pathlib import Path
from tempfile import TemporaryDirectory
from typing import Iterable
from ward import fixture

@fixture
def tmp_dir() -> Iterable[Path]: # pylint: disable=unused-variable
    directory = TemporaryDirectory()
    yield Path(directory.name)
    directory.cleanup()
```

__fixtures.io.global_tmp_dir.py
```python
#!/usr/bin/env python3

from pathlib import Path
from tempfile import TemporaryDirectory
from typing import Iterable
from ward import fixture, Scope

@fixture(scope = Scope.Global)
def global_tmp_dir() -> Iterable[Path]: # pylint: disable=unused-variable
    directory = TemporaryDirectory()
    yield Path(directory.name)
    directory.cleanup()
```

__fixtures.io.tmp_file.py
```python
#!/usr/bin/env python3

from typing import Callable, Dict, Any
from pathlib import Path
from shutil import copy
from urllib.request import urlretrieve
from ward import fixture, Scope
from __fixtures.base.config import config
from __fixtures.io.tmp_dir import tmp_dir
from __fixtures.io.global_tmp_dir import global_tmp_dir

@fixture(scope = Scope.Global)
def tmp_file( # pylint: disable=unused-variable
    config: Dict[str, Any] = config,
    tmp_dir: Path = tmp_dir,
    global_tmp_dir: Path = global_tmp_dir
) -> Callable[[str], Path]:
    def tmp_file(name: str) -> Path:
        global_tmp_file_path = global_tmp_dir / name
        if not global_tmp_file_path.is_file():
            urlretrieve(f"{config['TEST_FILES_DOMAIN']}/{name}", global_tmp_file_path)
        local_tmp_file_path = tmp_dir / name
        # For some reason tmp_dir fixture Path does not exist here after one test is finished
        print(tmp_dir.is_dir())
        copy(global_tmp_file_path, local_tmp_file_path)
        return local_tmp_file_path
    return tmp_file
```

aaaa__test.py
```python
...
from __fixtures.io.tmp_file import tmp_file

@test("test a")
def _( # pylint: disable=unused-variable
    tmp_file: Callable[[str], Path] = tmp_file,
    test_file: str = each(
        "latlon.bin",
        "tdpack5.bin",
        "topo.bin",
        "A803sn1d.hdf",
        "1994_256_FSD.nc"
    )
) -> None:
    tmp_file(test_file)

@test("test b")
def _( # pylint: disable=unused-variable, dangerous-default-value
    tmp_file: Callable[[str], Path] = tmp_file,
    test_files: List[str] = [
        "latlon.bin",
        "tdpack5.bin",
        "topo.bin",
        "A803sn1d.hdf",
        "1994_256_FSD.nc"
    ]
) -> None:
    for test_file in test_files:
        tmp_file(test_file)
```

The issue is with `tmp_file` fixture. For some reason `function` scope fixture (`tmp_dir`) isn't working properly. It should create temporary directories for `each test` and `global_tmp_dir` should create temporary directory once per all tests. Yet if we use multiple tests which import `tmp_file` fixture then only one test will successfully pass and another test fails with non existing directory exception

**Comment by darrenburns** [comment]
Global fixtures are only run once: immediately before the first time they're requested by a test. When the global fixture runs, it'll request its dependency fixtures run first so that it can use the values they provide.

By setting the scope of `tmp_file` to global, you're saying that fixture should only run once, and _therefore its dependencies can only run once too_, regardless of their scope.

Changing the scope of `tmp_file` to `Scope.Test` (the default scope), should give you the behaviour you're looking for. It'll let that fixture request its dependencies before each test. The `tmp_dir` will be able to be regenerated each test, and the `global_tmp_dir` will be generated the first time it's needed, and reused thereafter.

**Comment by mgzenitech** [comment]
Alrighty :) Then I guess one more question that I have is before closing this:

Is it possible to overwrite scope of fixture?

Something like:
```python
from ward import fixture, Scope
from __fixtures.io.tmp_dir import tmp_dir

global_tmp_dir = fixture(tmp_dir.?????, Scope.Global)
```

**Comment by darrenburns** [comment]
When you say overwrite a fixture, I'm guessing you mean obtain a copy of a pre-existing fixture but with a different scope?

If so, I'd recommend something like the following:

```python
def make_tmp_dir() -> Iterable[Path]: # pylint: disable=unused-variable
    directory = TemporaryDirectory()
    yield Path(directory.name)
    directory.cleanup()

@fixture
def tmp_dir():
    yield from make_tmp_dir()

@fixture(scope=Scope.Global)
def global_tmp_dir():
    yield from make_tmp_dir()
```

You extract the common logic into a generator function and then you can define your normal test-scoped fixture and your global-scoped fixture. Inside both of those fixtures, you just `yield from` the generator function.

You will now have two fixtures with the same logic and different scopes.
