### ISSUE TITLE
Request: relax upper bounds on dependency: rich

### ISSUE THREAD

**Issue by AndydeCleyre** [darrenburns/ward#362]
This may be something to think about for more than just rich, but rich in particular is:

1. seeing rapid development and releases
2. used by a whole lot of projects (which may be co-installed with ward)

Currently ward prohibits installation of the newest rich releases, which means if a project is requiring that new version of rich, an older version of ward must be used, which doesn't restrict the rich version as much. 

But this doesn't actually improve compatibility -- in fact it creates a cascading effect of installing/requiring older versions of more tools, increasing probability of in-practice incompatibility (as opposed to explicitly version-specified incompatibility) between new PyPI releases and very old ones.

See also:

- #323 
- https://github.com/darrenburns/ward/issues/300#issuecomment-1371304154

**Comment by AndydeCleyre** [comment]
Linking rich's [release notes](https://github.com/Textualize/rich/releases) here

**Comment by darrenburns** [comment]
Fixed in 0.67.2b0, sorry for the wait.

**Comment by AndydeCleyre** [comment]
Excellent, thanks!
