### ISSUE TITLE
Add ability to pass multiple directories to the --path option

### ISSUE THREAD

**Issue by darrenburns** [darrenburns/ward#37]
The `--path` option currently only supports a single argument. This means if you have two sibling directories of tests, you'd have to specify a path of `.` in order for them to be found. This is really inefficient, because it means ward will spend a lot of time looking in places for tests where they won't be found.

A better interface would be e.g.

```
ward --path ./test_dir_one ./test_dir_two
```

Command line input in this project is handled by the click library, which supports this functionality out of the box: https://click.palletsprojects.com/en/7.x/options/#multi-value-options

To implement this change, one option would be to alter the `get_info_for_modules` to take a `List[str]` instead of a `str` argument:

https://github.com/darrenburns/ward/blob/e323f7a3b08b1175694055d75c0554321b24f1e9/ward/collect.py#L16

Then passing that list through to `pkgutil.iter_modules`:

https://github.com/darrenburns/ward/blob/e323f7a3b08b1175694055d75c0554321b24f1e9/ward/collect.py#L18

**Comment by AlecJ** [comment]
Hey! Just made a PR for this. I added a note in the PR about allowing 0 arguments but let me know if you need anything else.
