### ISSUE TITLE
Add a Makefile to standardise things like formatting commands etc.

### ISSUE THREAD

**Issue by darrenburns** [darrenburns/ward#38]
A `Makefile` would be very useful to capture common commands like `black .`, `ward --path tests` and commands that are used in the build and release GitHub Actions.

**Comment by CodeMouse92** [comment]
I'm really interested in this project! Python and testing are two areas of expertise for me. I don't know what my sustained involvement will be, but I can do some stuff.

I think this would be a good starting task for me, as I've done this sort of thing *many many* times.  Where do I see the full list of commands you want run? GitHub Actions only shows logs for me.

**Comment by darrenburns** [comment]
Excellent, glad to hear it, I'd really appreciate the help! 😃 

The only things I can think of right now are things like `make format` (`black .`), `make lint` (runs flake8 stuff, which I haven't been dilligently paying attention to at the moment admitedly!), and `make test` (`ward --path "tests"`).

**Comment by darrenburns** [comment]
#80 has been merged, thanks @CodeMouse92!
