### ISSUE TITLE
Loosen dependencies

### ISSUE THREAD

**Issue by darrenburns** [darrenburns/ward#45]
Dependencies are too strict at the moment, meaning there's a high likelihood of a clash between ward itself and the dependencies of projects that use ward.

https://github.com/darrenburns/ward/blob/e7a9a4fca6ab7aac3b4ada839d6f2641d3436cea/setup.py#L21

**Comment by CodeMouse92** [comment]
I should be able to tackle this one, once my other PR is resolved.

**Comment by CodeMouse92** [comment]
Just to save a bit of time, do you know if these are the minimum versions?

**Comment by darrenburns** [comment]
Unfortunately I don't. These versions have been pinned for a while, and I haven't tried any lower versions.

**Comment by CodeMouse92** [comment]
Okay, no problem. I've got Python 3.6, 3.7, and 3.8 on my development machine. I'll see how far back I can take each without the tests breaking.
