### ISSUE TITLE
Output capturing eats up output from PDB

### ISSUE THREAD

**Issue by darrenburns** [darrenburns/ward#47]
The recent addition of output capturing resulted in a bug where when you run PDB during a test session, all of the output that PDB tries to write to the terminal is also captured lost. This makes debugging impossible.

**Comment by dodgyville** [comment]
Hi, what is the best way to debug a failing test? Is there a way to turn off output capturing so that pdb.set_trace() works?

**Comment by darrenburns** [comment]
Hi @dodgyville, if you use Ward version 0.30.0b0, you can pass the `--no-capture-output` flag via the command line, or update your `pyproject.toml` like so:

```toml
[tool.ward]
capture-output = false
```

Let me know if you have any issues :)
