### ISSUE TITLE
Using the docstring instead of the first positional argument of @test()?

### ISSUE THREAD

**Issue by jtrakk** [darrenburns/ward#59]
[Test function docstrings](https://jml.io/pages/test-docstrings.html) are a great place to put a description of the test. I am wondering if it is better to keep the test description in there instead of in the decorator`@test("...")`.

**Comment by darrenburns** [comment]
This is an interesting idea, but I'm inclined to keep the description in the decorator and leave the docstring open to contain more detailed descriptions for readers if necessary. I'd like the docstring to be something for readers of the tests, and the string in the decorators to be something for those who run the tests.
