### ISSUE TITLE
Ideas from `assay` test framework

### ISSUE THREAD

**Issue by jtrakk** [darrenburns/ward#60]
Brandon Rhodes has a [great talk about his experimental Assay framework](https://github.com/brandon-rhodes/assay).  It offers several features. Figured I'd mention them in case they inspire you :-).

From the [slides](https://rhodesmill.org/brandon/slides/2016-01-puppy/): 

1. Stable screen output
2. Speculative importation
3. Test functions
4. Fast assert introspection
5. Auto parallel processing
6. Dangling *.pyc detection
7. Simple test fixtures

**Comment by darrenburns** [comment]
Thanks for this, there's some really cool ideas in there!
