### ISSUE TITLE
Ignore virtualenv folders when searching for tests? Ignore folders in .gitignore?

### ISSUE THREAD

**Issue by darrenburns** [darrenburns/ward#81]
This was discovered after merging #80, which adds a Makefile which creates a venv inside the project directory. During test collection, ward recurses directories and may stumble across test modules not intended for it. Looking inside the virtualenv caused `ward` to fail. Running `ward --path tests` worked because it excluded the virtualenv from test collection.

<img width="924" alt="Screenshot 2020-01-19 at 00 56 48" src="https://user-images.githubusercontent.com/5740731/72672726-9b943000-3a56-11ea-8d2e-d1d451ac65b6.png">

I'm wondering whether it makes sense for ward to ignore virtualenvs or folders in the `.gitignore` when it looks for tests?

**Comment by CodeMouse92** [comment]
I wouldn't have Ward use `.gitignore` per-se (what if another VCS, or no VCS, is in use?) Instead, we should probably have something like `.wardignore`

**Comment by darrenburns** [comment]
This is mostly about the "zero-config" experience (i.e. running `ward` with no args), which I value quite a lot. The fact that the plain `ward` is failing if there's a virtualenv in the directory isn't ideal. 

There's a similar issue open at https://github.com/darrenburns/ward/issues/70 suggesting Ward could maintain a list of directories which would be ignored by default. For example `node_modules`, `.git`, or any other dot dirs.

R.e. `.wardignore`: the route I'd like to take Ward is towards supporting the standard `pyproject.toml`. Any option that could be supplied via a command line option can also be configured in there. That's similar to how `black` does it.

I'd envisage excluding directories to look something like:

```toml
[tool.ward]
exclude_dirs = ["dir1", "dir2"]
```

**Comment by CodeMouse92** [comment]
That could work.

To the aim of no-config, you could have Ward ignore anything in a `lib` directory by default, as that would (to my knowledge) *always* be where Python code files appear in a virtual environment. Then, that would have to be manually enabled in `pyproject.toml`.

**Comment by CodeMouse92** [comment]
So, based on all of that, I propose the following behavior:

* Anything listed in `.gitignore` or `.hgignore` would be ignored by default.
* Anything under a directory named `include`, `lib`, or `lib64` would be ignored by default.
* Anything in `exclude_dirs` under `pyproject.toml` would be ignored.
* Anything in `include_dirs` under `pyproject.toml` would *not* be ignored, regardless of the preceding.

**Comment by darrenburns** [comment]
That all seems reasonable. I'd also propose that we by default exclude `.hg` and `.git` directories, and consider this prior art: https://github.com/psf/black/blob/be49ac72a04dd70d3f496d3d062405ad4166ea0b/black.py#L60

**Comment by CodeMouse92** [comment]
Oh, definitely. That list is a good starting place.

**Comment by darrenburns** [comment]
`0.33.0b0` added the `--exclude` command line flag. There's still no default exclusions, however.

**Comment by rodolfolottin** [comment]
Is anyone working on it? If no, I could give it a try.

**Comment by darrenburns** [comment]
@rodolfolottin You're more than welcome to :)

As mentioned, the ability for the user to exclude directories is already implemented and released, so this would be defining a list of directories that are excluded by default, and providing a way for them to include them if required with `--include`. This comment (https://github.com/darrenburns/ward/issues/81#issuecomment-577346524) by @CodeMouse92 seems like sensible behaviour, but of course it's open for discussion.

Let me know if you have any questions!

**Comment by darrenburns** [comment]
site-packages are ignored as of Ward 0.44.0b0.

I think it'd still be great to ignore some dirs by default in the same way as Black does here https://github.com/psf/black/blob/be49ac72a04dd70d3f496d3d062405ad4166ea0b/black.py#L60

**Comment by marcoacierno** [comment]
Has `[tool.ward]` been implemented or it's still in discussion? I had this error

```
  File ".serverless/requirements/h11/tests/test_connection.py", line 1, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
```

because of `.serverless` and files in it

Having a way to specify what to ignore would be great :)

I also tried 

```
poetry run ward --exclude .serverless/
```

but it doesn't seem to work
