### ISSUE TITLE
Interactive watch mode

### ISSUE THREAD

**Issue by darrenburns** [darrenburns/ward#86]
Jest has a really nice interactive "watch" mode, which will re-run any tests that change. If you change a file that tests depend on, Jest can walk the dependency tree and work out which tests to run as a result.

**Comment by CodeMouse92** [comment]
My first guess is that this would involve maintaining a dictionary (that saves as a JSON file) that uses filenames/paths as keys, and a list of tests that ran on that file.

**Comment by darrenburns** [comment]
@CodeMouse92 Yeah, I was thinking of using something like coverage.py to determine the relationship between source files and tests, but I haven't fully thought this out.

Another thing I'm going to investigate is pytest-testmon. There's an interesting post here which I've skimmed over that gives some insight: https://testmon.org/determining-affected-tests.html

**Comment by darrenburns** [comment]
I've started working on this at #108.
