### ISSUE TITLE
Tell the user if their pyproject.toml file has been found and is being used

### ISSUE THREAD

**Issue by darrenburns** [darrenburns/ward#91]
Right now Ward supports config through `pyproject.toml`, but there's nothing in the output that indicates that the defaults from that file are being used. If a `pyproject.toml` is used, we should tell the user.

**Question:** should this be hidden behind a flag (possibly a `--verbose` flag)?

**Comment by mandarvaze** [comment]
@darrenburns 

I'm thinking we add a print/log statement [here](https://github.com/darrenburns/ward/blob/a2095d07b63f74a9372dc144ee70ec77ef1f2412/ward/config.py#L30) ?

Additionally, in two places **before** `return {}` we can print/log something like "Using default config"

Let me know if this makes sense - I'll make a PR

**Comment by darrenburns** [comment]
I think here would make most sense: https://github.com/darrenburns/ward/blob/a2095d07b63f74a9372dc144ee70ec77ef1f2412/ward/terminal.py#L226. I'm trying to keep the output limited to that file rather than scattering it all over the place.

In the case where we're using the default config, i.e. not pyproject config, I'd prefer if we just don't print anything.

**Comment by mandarvaze** [comment]
Thanks. 

Yours is definitely cleaner approach ;)
I'll study the code a little to figure out how to get pyproject path in the code you mentioned above.

**Comment by darrenburns** [comment]
Cool - it'll probably involve looking at the docs for Click and seeing if it's possible to pass the data returned from the callback into the wrapped function.

**Comment by mandarvaze** [comment]
I have a working solution ready, but it seems a lot of work to pass one string (toml path) to the ultimate "print" destination.
May be I am doing something wrong.
I'll submit a PR after following contributing guidelines.

**Comment by darrenburns** [comment]
Added in 0.40.0b0
