### ISSUE TITLE
Shell completion

### ISSUE THREAD

**Issue by darrenburns** [darrenburns/ward#97]
Integrate: https://github.com/click-contrib/click-completion

**Comment by Formartha** [comment]
Do you want to integrate it? what is the use case?

**Comment by darrenburns** [comment]
I would like to see it implemented as I think it's a nice productivity feature. In shells such as fish and zsh, if you install the completion script you will be able to tab through available options and see the help text as you type.

**Comment by Formartha** [comment]
Okay, I can try to implement it - I just need some initial guidance to start :) are there any channels other than Github to speak with each other?

**Comment by darrenburns** [comment]
Sure, I've created a gitter room that we can use. Please use the `code-help` room here: https://gitter.im/python-ward/community?utm_source=share-link&utm_medium=link&utm_campaign=share-link

**Comment by darrenburns** [comment]
Some initial guidance would be to take a look at the click-completion documentation, and you can find the `click` CLI specific stuff in Ward in `run.py`. For local development, you can get up and running using `flit install -s` (you'll need to have `flit` installed), which will install Ward such that you can edit and and won't need to constantly reinstall it. You can run the tests by just typing `ward`.
